"""Initial schema.

Creates the full Rift Lab model: identity (summoners, league_entries), normalized
Match-V5 storage (matches, match_teams, match_participants), the timeline layer
(timeline_frames, timeline_events), derived analytics (participant_features,
cohort_stats, map_risk_cells, roam_events, objective_setups), and operational
tables (ingest_jobs, ml_models).

Revision ID: 0001_initial
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cohort_key', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('specificity', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_stats')),
    sa.UniqueConstraint('cohort_key', 'metric', name='uq_cohort_metric')
    )
    op.create_index('ix_cohort_metric_spec', 'cohort_stats', ['metric', 'specificity'], unique=False)
    op.create_index(op.f('ix_cohort_stats_cohort_key'), 'cohort_stats', ['cohort_key'], unique=False)
    op.create_index(op.f('ix_cohort_stats_metric'), 'cohort_stats', ['metric'], unique=False)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_matches', sa.Integer(), nullable=False),
    sa.Column('matches_discovered', sa.Integer(), nullable=False),
    sa.Column('matches_ingested', sa.Integer(), nullable=False),
    sa.Column('matches_skipped', sa.Integer(), nullable=False),
    sa.Column('timelines_ingested', sa.Integer(), nullable=False),
    sa.Column('features_computed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_jobs'))
    )
    op.create_index(op.f('ix_ingest_jobs_puuid'), 'ingest_jobs', ['puuid'], unique=False)
    op.create_table('map_risk_cells',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.Column('cell_x', sa.Integer(), nullable=False),
    sa.Column('cell_y', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('tier_group', sa.String(length=16), nullable=False),
    sa.Column('horizon_seconds', sa.Integer(), nullable=False),
    sa.Column('exposures', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('baseline_risk', sa.Float(), nullable=False),
    sa.Column('lift', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(length=24), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_risk_cells')),
    sa.UniqueConstraint('grid_size', 'cell_x', 'cell_y', 'phase', 'role', 'tier_group', 'horizon_seconds', name='uq_risk_cell')
    )
    op.create_index('ix_risk_lookup', 'map_risk_cells', ['phase', 'role', 'tier_group'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('game_mode', sa.String(length=32), nullable=True),
    sa.Column('game_type', sa.String(length=32), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=True),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('winning_team_id', sa.Integer(), nullable=True),
    sa.Column('timeline_ingested', sa.Boolean(), nullable=False),
    sa.Column('features_computed', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_game_start'), 'matches', ['game_start'], unique=False)
    op.create_index(op.f('ix_matches_patch'), 'matches', ['patch'], unique=False)
    op.create_index('ix_matches_patch_queue', 'matches', ['patch', 'queue_id'], unique=False)
    op.create_index(op.f('ix_matches_platform'), 'matches', ['platform'], unique=False)
    op.create_index(op.f('ix_matches_queue_id'), 'matches', ['queue_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_importances', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models')),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=False)
    op.create_table('summoners',
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=True),
    sa.Column('tag_line', sa.String(length=16), nullable=True),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('summoner_id', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('revision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('puuid', name=op.f('pk_summoners'))
    )
    op.create_index(op.f('ix_summoners_platform'), 'summoners', ['platform'], unique=False)
    op.create_index('ix_summoners_riot_id', 'summoners', ['game_name', 'tag_line', 'platform'], unique=False)
    op.create_table('league_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('queue_type', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('division', sa.String(length=4), nullable=True),
    sa.Column('league_points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('hot_streak', sa.Boolean(), nullable=False),
    sa.Column('veteran', sa.Boolean(), nullable=False),
    sa.Column('inactive', sa.Boolean(), nullable=False),
    sa.Column('fresh_blood', sa.Boolean(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puuid'], ['summoners.puuid'], name=op.f('fk_league_entries_puuid_summoners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_entries')),
    sa.UniqueConstraint('puuid', 'queue_type', name='uq_league_entry_puuid_queue')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('riot_id_game_name', sa.String(length=64), nullable=True),
    sa.Column('riot_id_tagline', sa.String(length=16), nullable=True),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(length=32), nullable=True),
    sa.Column('champ_level', sa.Integer(), nullable=False),
    sa.Column('team_position', sa.String(length=16), nullable=False),
    sa.Column('individual_position', sa.String(length=16), nullable=True),
    sa.Column('lane', sa.String(length=16), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('gold_spent', sa.Integer(), nullable=False),
    sa.Column('total_minions_killed', sa.Integer(), nullable=False),
    sa.Column('neutral_minions_killed', sa.Integer(), nullable=False),
    sa.Column('total_damage_to_champions', sa.Integer(), nullable=False),
    sa.Column('physical_damage_to_champions', sa.Integer(), nullable=False),
    sa.Column('magic_damage_to_champions', sa.Integer(), nullable=False),
    sa.Column('true_damage_to_champions', sa.Integer(), nullable=False),
    sa.Column('total_damage_taken', sa.Integer(), nullable=False),
    sa.Column('damage_self_mitigated', sa.Integer(), nullable=False),
    sa.Column('total_heals_on_teammates', sa.Integer(), nullable=False),
    sa.Column('damage_dealt_to_objectives', sa.Integer(), nullable=False),
    sa.Column('damage_dealt_to_turrets', sa.Integer(), nullable=False),
    sa.Column('vision_score', sa.Integer(), nullable=False),
    sa.Column('wards_placed', sa.Integer(), nullable=False),
    sa.Column('wards_killed', sa.Integer(), nullable=False),
    sa.Column('detector_wards_placed', sa.Integer(), nullable=False),
    sa.Column('vision_wards_bought', sa.Integer(), nullable=False),
    sa.Column('turret_takedowns', sa.Integer(), nullable=False),
    sa.Column('dragon_takedowns', sa.Integer(), nullable=False),
    sa.Column('baron_takedowns', sa.Integer(), nullable=False),
    sa.Column('objectives_stolen', sa.Integer(), nullable=False),
    sa.Column('time_ccing_others', sa.Integer(), nullable=False),
    sa.Column('total_time_spent_dead', sa.Integer(), nullable=False),
    sa.Column('longest_time_spent_living', sa.Integer(), nullable=False),
    sa.Column('first_blood_kill', sa.Boolean(), nullable=False),
    sa.Column('first_tower_kill', sa.Boolean(), nullable=False),
    sa.Column('summoner_spell_1', sa.Integer(), nullable=True),
    sa.Column('summoner_spell_2', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('perks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rank_tier', sa.String(length=16), nullable=True),
    sa.Column('rank_division', sa.String(length=4), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('tier_group', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_participants_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_participants')),
    sa.UniqueConstraint('match_id', 'participant_id', name='uq_match_participant')
    )
    op.create_index(op.f('ix_match_participants_champion_id'), 'match_participants', ['champion_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    op.create_index(op.f('ix_match_participants_rank_tier'), 'match_participants', ['rank_tier'], unique=False)
    op.create_index(op.f('ix_match_participants_tier_group'), 'match_participants', ['tier_group'], unique=False)
    op.create_index('ix_participants_cohort', 'match_participants', ['team_position', 'champion_id', 'tier_group'], unique=False)
    op.create_index('ix_participants_puuid_match', 'match_participants', ['puuid', 'match_id'], unique=False)
    op.create_table('match_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('champion_kills', sa.Integer(), nullable=False),
    sa.Column('dragon_kills', sa.Integer(), nullable=False),
    sa.Column('baron_kills', sa.Integer(), nullable=False),
    sa.Column('herald_kills', sa.Integer(), nullable=False),
    sa.Column('tower_kills', sa.Integer(), nullable=False),
    sa.Column('inhibitor_kills', sa.Integer(), nullable=False),
    sa.Column('first_blood', sa.Boolean(), nullable=False),
    sa.Column('first_tower', sa.Boolean(), nullable=False),
    sa.Column('first_dragon', sa.Boolean(), nullable=False),
    sa.Column('first_baron', sa.Boolean(), nullable=False),
    sa.Column('bans', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_teams_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_teams')),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_team')
    )
    op.create_table('objective_setups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('objective_type', sa.String(length=32), nullable=False),
    sa.Column('objective_sub_type', sa.String(length=32), nullable=True),
    sa.Column('objective_ms', sa.Integer(), nullable=False),
    sa.Column('team_secured', sa.Boolean(), nullable=False),
    sa.Column('player_credited', sa.Boolean(), nullable=False),
    sa.Column('distance_30s', sa.Float(), nullable=True),
    sa.Column('distance_60s', sa.Float(), nullable=True),
    sa.Column('distance_90s', sa.Float(), nullable=True),
    sa.Column('arrival_lead_seconds', sa.Float(), nullable=True),
    sa.Column('wards_placed_window', sa.Integer(), nullable=False),
    sa.Column('wards_cleared_window', sa.Integer(), nullable=False),
    sa.Column('deaths_window', sa.Integer(), nullable=False),
    sa.Column('setup_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_objective_setups_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objective_setups'))
    )
    op.create_index('ix_obj_setup_match_puuid', 'objective_setups', ['match_id', 'puuid'], unique=False)
    op.create_index('ix_obj_setup_type', 'objective_setups', ['objective_type'], unique=False)
    op.create_index(op.f('ix_objective_setups_puuid'), 'objective_setups', ['puuid'], unique=False)
    op.create_table('participant_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('team_position', sa.String(length=16), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('tier_group', sa.String(length=16), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('duration_bucket', sa.String(length=8), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('gold_diff_10', sa.Float(), nullable=True),
    sa.Column('gold_diff_15', sa.Float(), nullable=True),
    sa.Column('xp_diff_10', sa.Float(), nullable=True),
    sa.Column('xp_diff_15', sa.Float(), nullable=True),
    sa.Column('cs_diff_10', sa.Float(), nullable=True),
    sa.Column('cs_diff_15', sa.Float(), nullable=True),
    sa.Column('cs_per_min', sa.Float(), nullable=False),
    sa.Column('cs_per_min_first_15', sa.Float(), nullable=True),
    sa.Column('gold_per_min', sa.Float(), nullable=False),
    sa.Column('damage_per_min', sa.Float(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('kill_participation', sa.Float(), nullable=True),
    sa.Column('early_deaths', sa.Integer(), nullable=False),
    sa.Column('deaths_per_10min', sa.Float(), nullable=False),
    sa.Column('solo_kills', sa.Integer(), nullable=False),
    sa.Column('solo_deaths', sa.Integer(), nullable=False),
    sa.Column('solo_kill_diff', sa.Integer(), nullable=False),
    sa.Column('damage_per_gold', sa.Float(), nullable=False),
    sa.Column('damage_share', sa.Float(), nullable=True),
    sa.Column('gold_share', sa.Float(), nullable=True),
    sa.Column('damage_taken_share', sa.Float(), nullable=True),
    sa.Column('rce_raw', sa.Float(), nullable=True),
    sa.Column('rce_z', sa.Float(), nullable=True),
    sa.Column('vision_score_per_min', sa.Float(), nullable=False),
    sa.Column('wards_placed_per_min', sa.Float(), nullable=False),
    sa.Column('wards_cleared_per_min', sa.Float(), nullable=False),
    sa.Column('control_wards_per_min', sa.Float(), nullable=False),
    sa.Column('objective_participation', sa.Float(), nullable=True),
    sa.Column('dragon_participation', sa.Float(), nullable=True),
    sa.Column('baron_herald_participation', sa.Float(), nullable=True),
    sa.Column('objective_setup_score', sa.Float(), nullable=True),
    sa.Column('deaths_before_objectives', sa.Integer(), nullable=False),
    sa.Column('team_gold_diff_15', sa.Float(), nullable=True),
    sa.Column('had_lead_at_15', sa.Boolean(), nullable=False),
    sa.Column('converted_lead', sa.Boolean(), nullable=False),
    sa.Column('time_ahead_share', sa.Float(), nullable=True),
    sa.Column('dpm_while_ahead', sa.Float(), nullable=True),
    sa.Column('dpm_while_behind', sa.Float(), nullable=True),
    sa.Column('cspm_while_ahead', sa.Float(), nullable=True),
    sa.Column('cspm_while_behind', sa.Float(), nullable=True),
    sa.Column('gold_diff_slope_10_20', sa.Float(), nullable=True),
    sa.Column('roam_count', sa.Integer(), nullable=False),
    sa.Column('roam_value_total', sa.Float(), nullable=False),
    sa.Column('roam_value_per_roam', sa.Float(), nullable=True),
    sa.Column('roam_cs_sacrificed', sa.Float(), nullable=False),
    sa.Column('roam_success_rate', sa.Float(), nullable=True),
    sa.Column('mean_position_risk', sa.Float(), nullable=True),
    sa.Column('expected_deaths', sa.Float(), nullable=True),
    sa.Column('deaths_above_expected', sa.Float(), nullable=True),
    sa.Column('high_risk_exposure_share', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_participant_features_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_features')),
    sa.UniqueConstraint('match_id', 'puuid', name='uq_features_match_puuid')
    )
    op.create_index('ix_features_cohort', 'participant_features', ['team_position', 'champion_id', 'tier_group', 'patch'], unique=False)
    op.create_index('ix_features_puuid_patch', 'participant_features', ['puuid', 'patch'], unique=False)
    op.create_index(op.f('ix_participant_features_champion_id'), 'participant_features', ['champion_id'], unique=False)
    op.create_index(op.f('ix_participant_features_patch'), 'participant_features', ['patch'], unique=False)
    op.create_index(op.f('ix_participant_features_puuid'), 'participant_features', ['puuid'], unique=False)
    op.create_index(op.f('ix_participant_features_team_position'), 'participant_features', ['team_position'], unique=False)
    op.create_index(op.f('ix_participant_features_tier_group'), 'participant_features', ['tier_group'], unique=False)
    op.create_table('roam_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('puuid', sa.String(length=78), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('target_zone', sa.String(length=24), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('objectives', sa.Integer(), nullable=False),
    sa.Column('gold_gained', sa.Float(), nullable=False),
    sa.Column('xp_gained', sa.Float(), nullable=False),
    sa.Column('cs_sacrificed', sa.Float(), nullable=False),
    sa.Column('xp_sacrificed', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_roam_events_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roam_events'))
    )
    op.create_index(op.f('ix_roam_events_puuid'), 'roam_events', ['puuid'], unique=False)
    op.create_index('ix_roams_match_puuid', 'roam_events', ['match_id', 'puuid'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('killer_id', sa.Integer(), nullable=True),
    sa.Column('victim_id', sa.Integer(), nullable=True),
    sa.Column('assisting_participant_ids', sa.JSON().with_variant(postgresql.ARRAY(sa.Integer()), 'postgresql'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('monster_type', sa.String(length=32), nullable=True),
    sa.Column('monster_sub_type', sa.String(length=32), nullable=True),
    sa.Column('building_type', sa.String(length=32), nullable=True),
    sa.Column('tower_type', sa.String(length=32), nullable=True),
    sa.Column('lane_type', sa.String(length=32), nullable=True),
    sa.Column('ward_type', sa.String(length=32), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('kill_type', sa.String(length=32), nullable=True),
    sa.Column('bounty', sa.Integer(), nullable=True),
    sa.Column('shutdown_bounty', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_timeline_events_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index('ix_events_match_ts', 'timeline_events', ['match_id', 'timestamp_ms'], unique=False)
    op.create_index('ix_events_match_type', 'timeline_events', ['match_id', 'type'], unique=False)
    op.create_index('ix_events_victim', 'timeline_events', ['match_id', 'victim_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_type'), 'timeline_events', ['type'], unique=False)
    op.create_table('timeline_frames',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('total_gold', sa.Integer(), nullable=False),
    sa.Column('current_gold', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('minions_killed', sa.Integer(), nullable=False),
    sa.Column('jungle_minions_killed', sa.Integer(), nullable=False),
    sa.Column('time_enemy_spent_controlled', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('damage_done_to_champions', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_timeline_frames_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_frames')),
    sa.UniqueConstraint('match_id', 'participant_id', 'timestamp_ms', name='uq_frame')
    )
    op.create_index('ix_frames_lookup', 'timeline_frames', ['match_id', 'participant_id', 'timestamp_ms'], unique=False)
    op.create_index('ix_frames_match_minute', 'timeline_frames', ['match_id', 'minute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_frames_match_minute', table_name='timeline_frames')
    op.drop_index('ix_frames_lookup', table_name='timeline_frames')
    op.drop_table('timeline_frames')
    op.drop_index(op.f('ix_timeline_events_type'), table_name='timeline_events')
    op.drop_index('ix_events_victim', table_name='timeline_events')
    op.drop_index('ix_events_match_type', table_name='timeline_events')
    op.drop_index('ix_events_match_ts', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_roams_match_puuid', table_name='roam_events')
    op.drop_index(op.f('ix_roam_events_puuid'), table_name='roam_events')
    op.drop_table('roam_events')
    op.drop_index(op.f('ix_participant_features_tier_group'), table_name='participant_features')
    op.drop_index(op.f('ix_participant_features_team_position'), table_name='participant_features')
    op.drop_index(op.f('ix_participant_features_puuid'), table_name='participant_features')
    op.drop_index(op.f('ix_participant_features_patch'), table_name='participant_features')
    op.drop_index(op.f('ix_participant_features_champion_id'), table_name='participant_features')
    op.drop_index('ix_features_puuid_patch', table_name='participant_features')
    op.drop_index('ix_features_cohort', table_name='participant_features')
    op.drop_table('participant_features')
    op.drop_index(op.f('ix_objective_setups_puuid'), table_name='objective_setups')
    op.drop_index('ix_obj_setup_type', table_name='objective_setups')
    op.drop_index('ix_obj_setup_match_puuid', table_name='objective_setups')
    op.drop_table('objective_setups')
    op.drop_table('match_teams')
    op.drop_index('ix_participants_puuid_match', table_name='match_participants')
    op.drop_index('ix_participants_cohort', table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_tier_group'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_rank_tier'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_champion_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_table('league_entries')
    op.drop_index('ix_summoners_riot_id', table_name='summoners')
    op.drop_index(op.f('ix_summoners_platform'), table_name='summoners')
    op.drop_table('summoners')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_matches_queue_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_platform'), table_name='matches')
    op.drop_index('ix_matches_patch_queue', table_name='matches')
    op.drop_index(op.f('ix_matches_patch'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_start'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_risk_lookup', table_name='map_risk_cells')
    op.drop_table('map_risk_cells')
    op.drop_index(op.f('ix_ingest_jobs_puuid'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_cohort_stats_metric'), table_name='cohort_stats')
    op.drop_index(op.f('ix_cohort_stats_cohort_key'), table_name='cohort_stats')
    op.drop_index('ix_cohort_metric_spec', table_name='cohort_stats')
    op.drop_table('cohort_stats')
    # ### end Alembic commands ###
