import { Card, Disclaimer, EmptyState, PercentileBar, PlayerTabs, Stat } from "@/components/ui";
import { api } from "@/lib/api";
import {
  effectivePercentile,
  formatMetric,
  formatPercent,
  ordinal,
  percentileTone,
} from "@/lib/format";
import type { AdvancedStats, CohortComparison } from "@/lib/types";

import { PlayerHeader } from "../player-header";
import { resolvePlayer, type PlayerRouteParams } from "../player-data";

export const dynamic = "force-dynamic";

/** Metrics that are lower-is-better; mirrors the backend's LOWER_IS_BETTER. */
const LOWER_IS_BETTER = new Set([
  "early_deaths",
  "deaths_per_10min",
  "deaths_before_objectives",
  "roam_cs_sacrificed",
  "mean_position_risk",
  "deaths_above_expected",
  "high_risk_exposure_share",
]);

const GROUPS: Array<{ title: string; blurb: string; metrics: string[] }> = [
  {
    title: "Laning",
    blurb: "Differences against the lane opponent at fixed marks, and farm rate.",
    metrics: [
      "gold_diff_10", "gold_diff_15", "xp_diff_10", "xp_diff_15",
      "cs_diff_10", "cs_diff_15", "cs_per_min", "cs_per_min_first_15",
      "gold_diff_slope_10_20",
    ],
  },
  {
    title: "Combat & efficiency",
    blurb: "What the player produces, and what it cost to produce it.",
    metrics: [
      "kill_participation", "damage_per_min", "damage_per_gold", "rce_raw",
      "damage_share", "gold_share", "solo_kill_diff", "early_deaths", "deaths_per_10min",
    ],
  },
  {
    title: "Vision",
    blurb: "Vision placed, cleared and paid for, per minute.",
    metrics: [
      "vision_score_per_min", "wards_placed_per_min",
      "wards_cleared_per_min", "control_wards_per_min",
    ],
  },
  {
    title: "Objectives",
    blurb: "Presence and setup around neutral objectives.",
    metrics: [
      "objective_participation", "dragon_participation",
      "baron_herald_participation", "objective_setup_score", "deaths_before_objectives",
    ],
  },
  {
    title: "Game state",
    blurb: "The two different games a player plays: ahead, and behind.",
    metrics: [
      "time_ahead_share", "dpm_while_ahead", "dpm_while_behind",
      "cspm_while_ahead", "cspm_while_behind",
    ],
  },
  {
    title: "Roaming",
    blurb: "Value generated by leaving lane, net of the farm given up.",
    metrics: ["roam_count", "roam_value_per_roam", "roam_cs_sacrificed", "roam_success_rate"],
  },
  {
    title: "Positioning risk",
    blurb: "Model-derived. Estimates, not measurements.",
    metrics: ["mean_position_risk", "deaths_above_expected", "high_risk_exposure_share"],
  },
];

function MetricRow({ metric }: { metric: CohortComparison }) {
  const higherIsBetter = !LOWER_IS_BETTER.has(metric.metric);
  const effective = effectivePercentile(metric.percentile, higherIsBetter);
  return (
    <tr>
      <td>
        <div>{metric.label}</div>
        {metric.is_fallback_cohort && (
          <div className="text-xs text-ink-faint">broader cohort used</div>
        )}
      </td>
      <td className="stat">{formatMetric(metric.metric, metric.value)}</td>
      <td className="stat text-ink-muted">{formatMetric(metric.metric, metric.cohort_median)}</td>
      <td className="stat text-ink-faint">
        {formatMetric(metric.metric, metric.cohort_p25)} –{" "}
        {formatMetric(metric.metric, metric.cohort_p75)}
      </td>
      <td className="w-32">
        <div className="flex items-center gap-2">
          <PercentileBar value={effective} />
          <span className={`w-10 shrink-0 text-right text-xs ${percentileTone(effective)}`}>
            {effective !== null ? ordinal(effective) : "—"}
          </span>
        </div>
      </td>
      <td className="stat text-xs text-ink-faint">{metric.cohort_n}</td>
    </tr>
  );
}

export default async function AdvancedStatsPage({
  params,
}: {
  params: Promise<PlayerRouteParams>;
}) {
  const routeParams = await params;
  const { player, riotId } = await resolvePlayer(routeParams);

  let stats: AdvancedStats | null = null;
  let profile = null;
  try {
    [stats, profile] = await Promise.all([
      api.advanced(player.puuid),
      api.profile(player.puuid).catch(() => null),
    ]);
  } catch {
    stats = null;
  }

  const byMetric = new Map((stats?.metrics ?? []).map((m) => [m.metric, m]));
  const rce = stats?.resource_conversion;

  return (
    <div>
      <PlayerHeader
        player={player}
        riotId={riotId}
        platform={routeParams.platform}
        profile={profile}
      />
      <PlayerTabs platform={routeParams.platform} riotId={riotId} active="advanced" />

      {!stats ? (
        <EmptyState title="No advanced statistics yet">
          These are derived from ingested timelines. Ingest matches first.
        </EmptyState>
      ) : (
        <div className="space-y-5">
          {rce && (
            <Card
              title="Resource Conversion Efficiency"
              subtitle="Output share ÷ resource share. 1.0 means the player converted exactly their share of the team's gold into their share of its damage."
            >
              <div className="grid gap-4 sm:grid-cols-4">
                <Stat
                  label="RCE"
                  value={rce.rce_raw_mean?.toFixed(2) ?? "—"}
                  hint={
                    rce.percentile !== null
                      ? `${ordinal(rce.percentile)} percentile · n=${rce.cohort_n}`
                      : undefined
                  }
                  tone={
                    rce.rce_raw_mean !== null && rce.rce_raw_mean >= 1.05
                      ? "text-good"
                      : rce.rce_raw_mean !== null && rce.rce_raw_mean <= 0.9
                        ? "text-warn"
                        : ""
                  }
                />
                <Stat
                  label="Damage share"
                  value={formatPercent(rce.damage_share_mean)}
                  hint="of team damage"
                />
                <Stat
                  label="Gold share"
                  value={formatPercent(rce.gold_share_mean)}
                  hint="of team gold"
                />
                <Stat
                  label="Champion-normalised"
                  value={rce.rce_z_mean !== null ? rce.rce_z_mean.toFixed(2) : "—"}
                  hint="z vs same champion & rank"
                />
              </div>
              {rce.interpretation && (
                <p className="mt-4 text-sm text-ink-muted">{rce.interpretation}</p>
              )}
              <Disclaimer>
                Raw RCE already controls for game length and team strength, since
                both sides of the ratio are shares. It does not control for
                champion — a marksman converts gold to damage better than an
                enchanter — which is what the normalised column is for.
              </Disclaimer>
            </Card>
          )}

          {GROUPS.map((group) => {
            const rows = group.metrics
              .map((m) => byMetric.get(m))
              .filter((m): m is CohortComparison => m !== undefined);
            if (rows.length === 0) return null;
            return (
              <Card key={group.title} title={group.title} subtitle={group.blurb}>
                <div className="scroll-x">
                  <table className="data">
                    <thead>
                      <tr>
                        <th>Metric</th>
                        <th>Player</th>
                        <th>Cohort median</th>
                        <th>Cohort P25–P75</th>
                        <th>Percentile</th>
                        <th>n</th>
                      </tr>
                    </thead>
                    <tbody>
                      {rows.map((metric) => (
                        <MetricRow key={metric.metric} metric={metric} />
                      ))}
                    </tbody>
                  </table>
                </div>
              </Card>
            );
          })}

          <Disclaimer>
            Cohorts control for role, champion, rank band, patch and game length.
            Where the fully specified cohort has too few observations the
            comparison falls back to a broader one, which is flagged on the row.
            Percentiles are oriented so that a higher bar always means better.
          </Disclaimer>
        </div>
      )}
    </div>
  );
}
