import Link from "next/link";

import { DiffChart, GoldXpChart } from "@/components/charts";
import { RiftMap } from "@/components/rift-map";
import { Badge, Card, Disclaimer, EmptyState, ErrorNotice, Stat } from "@/components/ui";
import { api } from "@/lib/api";
import {
  formatDate,
  formatDuration,
  formatMetric,
  formatPercent,
  formatSigned,
  roleLabel,
  zoneLabel,
} from "@/lib/format";
import type { MatchAnalysis, Observation } from "@/lib/types";

export const dynamic = "force-dynamic";

const SEVERITY_TONE: Record<Observation["severity"], "good" | "bad" | "warn" | "neutral"> = {
  strength: "good",
  priority: "bad",
  watch: "warn",
  neutral: "neutral",
};

function eventLabel(event: MatchAnalysis["events"][number]): string {
  if (event.type === "CHAMPION_KILL") {
    return `${event.killer ?? "?"} killed ${event.victim ?? "?"}`;
  }
  if (event.type === "ELITE_MONSTER_KILL") {
    const name = event.monster_sub_type ?? event.monster_type ?? "Objective";
    return `${name.replace(/_/g, " ").toLowerCase()} taken`;
  }
  if (event.type === "BUILDING_KILL") {
    return `${(event.lane_type ?? "").replace(/_/g, " ").toLowerCase()} turret destroyed`;
  }
  return event.type;
}

export default async function MatchAnalysisPage({
  params,
  searchParams,
}: {
  params: Promise<{ matchId: string }>;
  searchParams: Promise<{ puuid?: string; platform?: string; riotId?: string }>;
}) {
  const { matchId } = await params;
  const { puuid, platform, riotId } = await searchParams;

  if (!puuid) {
    return (
      <EmptyState title="Which player?">
        A match analysis is always from one player’s point of view. Open it from a
        player’s match history so the page knows whose game to analyse.
      </EmptyState>
    );
  }

  let analysis: MatchAnalysis | null = null;
  let error: string | null = null;
  try {
    analysis = await api.matchAnalysis(matchId, puuid);
  } catch (e) {
    error = e instanceof Error ? e.message : "Could not load the match";
  }

  if (!analysis) {
    return <ErrorNotice title="Match unavailable" message={error ?? "Unknown error"} />;
  }

  const { match, player, lane_opponent: opponent, timeline, deaths, roams } = analysis;
  const playerTeam = analysis.teams.find((t) => t.team_id === player.team_id);
  const enemyTeam = analysis.teams.find((t) => t.team_id !== player.team_id);

  const deathMarkers = deaths
    .filter((d) => d.position?.x != null && d.position?.y != null)
    .map((d) => ({ x: d.position!.x as number, y: d.position!.y as number }));

  const pathCells = timeline
    .filter((point) => point.position?.x != null && point.position?.y != null)
    .map((point) => ({
      cell_x: Math.min(31, Math.floor(((point.position!.x as number) / 15000) * 32)),
      cell_y: Math.min(31, Math.floor(((point.position!.y as number) / 15000) * 32)),
      intensity: 1,
      label: `Minute ${point.minute}`,
    }));

  const backHref =
    platform && riotId
      ? `/player/${platform}/${encodeURIComponent(riotId)}/matches`
      : undefined;

  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-2xl font-semibold tracking-tight">
              {player.champion_name ?? player.champion_id}
            </h1>
            <Badge tone={player.win ? "good" : "bad"}>{player.win ? "Victory" : "Defeat"}</Badge>
            <Badge>{roleLabel(player.team_position)}</Badge>
            <Badge>{match.queue_name}</Badge>
            <Badge>Patch {match.patch}</Badge>
          </div>
          <p className="mt-1 text-sm text-ink-muted">
            {formatDate(match.game_start)} · {formatDuration(match.duration_seconds)} ·{" "}
            {match.match_id}
            {opponent && ` · versus ${opponent.champion_name ?? opponent.champion_id}`}
          </p>
        </div>
        {backHref && (
          <Link href={backHref} className="link text-sm">
            ← Match history
          </Link>
        )}
      </header>

      {analysis.observations.length > 0 && (
        <Card
          title="Coaching observations"
          subtitle="Generated by comparing this game's derived metrics against peers in the same role, champion, rank band, patch and game length."
        >
          <ul className="space-y-3">
            {analysis.observations.map((observation) => (
              <li key={observation.metric} className="flex gap-3">
                <Badge tone={SEVERITY_TONE[observation.severity]}>
                  {observation.severity === "priority"
                    ? "Priority"
                    : observation.severity === "watch"
                      ? "Watch"
                      : observation.severity === "strength"
                        ? "Strength"
                        : "Note"}
                </Badge>
                <div className="min-w-0">
                  <p className="text-sm font-medium">{observation.headline}</p>
                  <p className="mt-0.5 text-sm text-ink-muted">{observation.detail}</p>
                </div>
              </li>
            ))}
          </ul>
        </Card>
      )}

      <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-6">
        <Card className="sm:col-span-3 lg:col-span-6">
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
            <Stat
              label="K / D / A"
              value={`${player.kills}/${player.deaths}/${player.assists}`}
              hint={`${formatPercent(player.kill_participation)} kill participation`}
            />
            <Stat
              label="CS"
              value={player.cs}
              hint={`${(player.cs / (match.duration_seconds / 60)).toFixed(1)} per min`}
            />
            <Stat
              label="Gold"
              value={player.gold_earned.toLocaleString()}
              hint={`${(player.gold_earned / (match.duration_seconds / 60)).toFixed(0)} per min`}
            />
            <Stat
              label="Damage"
              value={player.damage_to_champions.toLocaleString()}
              hint={`${(player.damage_to_champions / Math.max(player.gold_earned, 1)).toFixed(2)} per gold`}
            />
            <Stat
              label="Vision"
              value={player.vision_score}
              hint={`${player.wards_placed} placed, ${player.wards_killed} cleared`}
            />
            <Stat
              label="Objectives"
              value={`${playerTeam?.dragon_kills ?? 0}D ${playerTeam?.baron_kills ?? 0}B`}
              hint={`vs ${enemyTeam?.dragon_kills ?? 0}D ${enemyTeam?.baron_kills ?? 0}B`}
            />
          </div>
        </Card>
      </div>

      {timeline.length > 0 && (
        <div className="grid gap-5 lg:grid-cols-2">
          <Card title="Gold and XP" subtitle="Cumulative, sampled once per minute">
            <GoldXpChart data={timeline} />
          </Card>
          <Card
            title="Gold difference vs lane opponent"
            subtitle={
              opponent
                ? `Against ${opponent.champion_name ?? opponent.champion_id}`
                : "No lane opponent could be paired for this game"
            }
          >
            <DiffChart data={timeline} dataKey="gold_diff" label="Gold difference" />
          </Card>
          <Card title="CS difference vs lane opponent">
            <DiffChart data={timeline} dataKey="cs_diff" label="CS difference" />
          </Card>
          <Card title="Team gold difference" subtitle="The game state the player was playing in">
            <DiffChart data={timeline} dataKey="team_gold_diff" label="Team gold difference" />
          </Card>
        </div>
      )}

      <div className="grid gap-5 lg:grid-cols-2">
        <Card
          title="Deaths in context"
          subtitle="Each death with the region it happened in and the risk the model assigned to that position beforehand."
        >
          {deaths.length === 0 ? (
            <p className="text-sm text-ink-muted">No deaths in this game.</p>
          ) : (
            <div className="scroll-x">
              <table className="data">
                <thead>
                  <tr>
                    <th>Min</th>
                    <th>Region</th>
                    <th>Killed by</th>
                    <th>Type</th>
                    <th>Risk there</th>
                    <th>Team gold</th>
                  </tr>
                </thead>
                <tbody>
                  {deaths.map((death, i) => (
                    <tr key={i}>
                      <td className="stat">{death.minute}</td>
                      <td>{death.zone ? zoneLabel(death.zone) : "—"}</td>
                      <td className="text-ink-muted">{death.killer ?? "—"}</td>
                      <td>
                        {death.solo_death ? (
                          <Badge tone="warn">Solo</Badge>
                        ) : (
                          <span className="text-ink-faint">+{death.assist_count} assists</span>
                        )}
                      </td>
                      <td className="stat">
                        {death.risk_at_position !== null
                          ? formatPercent(death.risk_at_position, 1)
                          : "—"}
                      </td>
                      <td
                        className={`stat ${
                          (death.team_gold_diff ?? 0) > 0 ? "text-good" : "text-bad"
                        }`}
                      >
                        {formatSigned(death.team_gold_diff)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>

        <Card
          title="Movement and deaths"
          subtitle="Position samples across the game, with deaths marked."
        >
          <RiftMap
            cells={pathCells}
            markers={deathMarkers}
            gridSize={32}
            legendLabel="Time spent"
            markerLabel="Deaths"
            height={380}
          />
        </Card>
      </div>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card
          title="Objective setup"
          subtitle="Where the player was in the 90 seconds before each neutral objective."
        >
          {analysis.objective_setups.length === 0 ? (
            <p className="text-sm text-ink-muted">No neutral objectives in this game.</p>
          ) : (
            <div className="scroll-x">
              <table className="data">
                <thead>
                  <tr>
                    <th>Min</th>
                    <th>Objective</th>
                    <th>Result</th>
                    <th>Dist @-60s</th>
                    <th>Arrived</th>
                    <th>Wards</th>
                    <th>Setup</th>
                  </tr>
                </thead>
                <tbody>
                  {analysis.objective_setups.map((setup, i) => (
                    <tr key={i}>
                      <td className="stat">{setup.minute}</td>
                      <td>
                        {(setup.objective_sub_type ?? setup.objective_type)
                          .replace(/_/g, " ")
                          .toLowerCase()}
                      </td>
                      <td className={setup.team_secured ? "text-good" : "text-bad"}>
                        {setup.team_secured ? "Secured" : "Lost"}
                        {setup.player_credited && (
                          <span className="ml-1 text-xs text-ink-faint">(credited)</span>
                        )}
                      </td>
                      <td className="stat text-ink-muted">
                        {setup.distance_60s !== null ? setup.distance_60s.toFixed(0) : "—"}
                      </td>
                      <td className="stat">
                        {setup.arrival_lead_seconds !== null
                          ? `${setup.arrival_lead_seconds.toFixed(0)}s early`
                          : "absent"}
                      </td>
                      <td className="stat text-ink-muted">
                        {setup.wards_placed_window + setup.wards_cleared_window}
                      </td>
                      <td className="stat">
                        {setup.setup_score !== null ? setup.setup_score.toFixed(2) : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <Disclaimer>
            Positions between Riot’s one-minute frames are linearly interpolated,
            so arrival timing is an estimate at roughly frame resolution. The setup
            score is a weighted summary of arrival, vision and survival, not a
            fitted quantity.
          </Disclaimer>
        </Card>

        <Card
          title="Roams"
          subtitle="Excursions away from lane, valued against what the player would have gained staying."
        >
          {roams.length === 0 ? (
            <p className="text-sm text-ink-muted">
              No roams detected (junglers are excluded — they have no lane to leave).
            </p>
          ) : (
            <div className="scroll-x">
              <table className="data">
                <thead>
                  <tr>
                    <th>Window</th>
                    <th>Destination</th>
                    <th>K/A/D</th>
                    <th>CS given up</th>
                    <th>Value</th>
                    <th>vs expected</th>
                  </tr>
                </thead>
                <tbody>
                  {roams.map((roam, i) => (
                    <tr key={i}>
                      <td className="stat whitespace-nowrap">
                        {roam.start_minute}–{roam.end_minute}m
                      </td>
                      <td>{zoneLabel(roam.target_zone)}</td>
                      <td className="stat">
                        {roam.kills}/{roam.assists}/{roam.deaths}
                      </td>
                      <td className="stat text-ink-muted">{roam.cs_sacrificed.toFixed(1)}</td>
                      <td className={`stat ${roam.value > 0 ? "text-good" : "text-bad"}`}>
                        {formatSigned(roam.value)}
                      </td>
                      <td
                        className={`stat ${
                          (roam.efficiency ?? 0) > 0 ? "text-good" : "text-bad"
                        }`}
                      >
                        {formatSigned(roam.efficiency)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <Disclaimer>
            Value is in gold-equivalent units: resources gained during the window
            minus what the player’s own in-lane rate would have produced, plus
            objective credit, minus a fixed cost per death.
          </Disclaimer>
        </Card>
      </div>

      <Card title="Derived metrics for this game">
        <div className="scroll-x">
          <table className="data">
            <thead>
              <tr>
                <th>Metric</th>
                <th>Value</th>
                <th>Cohort median</th>
                <th>Percentile</th>
                <th>n</th>
              </tr>
            </thead>
            <tbody>
              {analysis.cohort_comparisons.map((row) => (
                <tr key={row.metric}>
                  <td>{row.label}</td>
                  <td className="stat">{formatMetric(row.metric, row.value)}</td>
                  <td className="stat text-ink-muted">
                    {formatMetric(row.metric, row.cohort_median)}
                  </td>
                  <td className="stat">
                    {row.percentile !== null ? `${row.percentile.toFixed(0)}` : "—"}
                  </td>
                  <td className="stat text-ink-faint">{row.cohort_n}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Card title="Match timeline" subtitle="Kills, objectives and turrets, in order">
        <ol className="scroll-x max-h-96 space-y-1 overflow-y-auto text-sm">
          {analysis.events.map((event, i) => (
            <li
              key={i}
              className={`flex items-baseline gap-3 rounded px-2 py-1 ${
                event.involved_player ? "bg-accent/10" : ""
              }`}
            >
              <span className="stat w-10 shrink-0 text-xs text-ink-faint">{event.minute}m</span>
              <span
                className={
                  event.killer_team_id === player.team_id ? "text-good" : "text-ink-muted"
                }
              >
                {eventLabel(event)}
              </span>
              {event.zone && (
                <span className="text-xs text-ink-faint">{zoneLabel(event.zone)}</span>
              )}
              {event.involved_player && <Badge tone="accent">You</Badge>}
            </li>
          ))}
        </ol>
      </Card>

      <Card title="Scoreboard">
        <div className="scroll-x">
          <table className="data">
            <thead>
              <tr>
                <th>Team</th>
                <th>Champion</th>
                <th>Role</th>
                <th>K/D/A</th>
                <th>CS</th>
                <th>Gold</th>
                <th>Damage</th>
                <th>Vision</th>
              </tr>
            </thead>
            <tbody>
              {analysis.participants.map((p) => (
                <tr key={p.participant_id} className={p.puuid === player.puuid ? "bg-accent/10" : ""}>
                  <td className={p.team_id === 100 ? "text-accent" : "text-bad"}>
                    {p.team_id === 100 ? "Blue" : "Red"}
                  </td>
                  <td>{p.champion_name ?? p.champion_id}</td>
                  <td className="text-ink-muted">{roleLabel(p.team_position)}</td>
                  <td className="stat">
                    {p.kills}/{p.deaths}/{p.assists}
                  </td>
                  <td className="stat">{p.cs}</td>
                  <td className="stat">{p.gold_earned.toLocaleString()}</td>
                  <td className="stat">{p.damage_to_champions.toLocaleString()}</td>
                  <td className="stat">{p.vision_score}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
